apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-management-deployment
  labels:
    app: media-management
  namespace: kube-poc-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-management
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: media-management
    spec:
      containers:
      - name: media-management-container
        resources:
          #          limits:
          #            cpu: 2
          #            memory: 1024
        image: 127.0.0.1:5555/media-management-dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5100
      # automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: media-management-service
  labels:
    app: media-management
  namespace: kube-poc-dev
spec:
  type: ClusterIP
  selector:
    app: media-management
  ports:
  - port: 5100
    targetPort: 5100
    # nodePort: 30002
