apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  labels:
    app: user-management
  namespace: kube-poc-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management-container
          image: 127.0.0.1:5555/user-management-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5101
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management
  namespace: kube-poc-dev
spec:
  type: ClusterIP
  selector:
    app: user-management
  ports:
  - port: 5101
    targetPort: 5101
    # nodePort: 30002
